[build]
  command = "npm run build"
  publish = "dist/eventos/browser"

[build.environment]
  # Esto es vital para que ignore el error de SSR que te salía antes
  NETLIFY_SKIP_ANGULAR_RUNTIME = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200